-- Kingston Estampados - Script inicial generado 2025-10-14 20:38:26 UTC
DROP DATABASE IF EXISTS kingston_estampados;
CREATE DATABASE kingston_estampados CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
USE kingston_estampados;


-- Accesos / Personas
CREATE TABLE rol (
  id_rol TINYINT PRIMARY KEY AUTO_INCREMENT,
  nombre VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE usuario (
  id_usuario BIGINT PRIMARY KEY AUTO_INCREMENT,
  email VARCHAR(120) NOT NULL UNIQUE,
  hash_password VARCHAR(255) NOT NULL,
  nombre VARCHAR(120) NOT NULL,
  telefono VARCHAR(30) NULL,
  activo TINYINT(1) NOT NULL DEFAULT 1,
  creado_en TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE usuario_rol (
  id_usuario BIGINT NOT NULL,
  id_rol TINYINT NOT NULL,
  PRIMARY KEY (id_usuario, id_rol),
  CONSTRAINT fk_ur_user FOREIGN KEY (id_usuario) REFERENCES usuario(id_usuario),
  CONSTRAINT fk_ur_rol FOREIGN KEY (id_rol) REFERENCES rol(id_rol)
);

CREATE TABLE cliente (
  id_cliente BIGINT PRIMARY KEY AUTO_INCREMENT,
  rut VARCHAR(15) NULL,
  razon_social VARCHAR(150) NULL,
  nombre_contacto VARCHAR(150) NULL,
  email VARCHAR(120) NULL,
  telefono VARCHAR(30) NULL,
  direccion VARCHAR(200) NULL,
  comuna VARCHAR(80) NULL,
  ciudad VARCHAR(80) NULL,
  id_usuario BIGINT NULL,
  creado_en TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_cliente_usuario FOREIGN KEY (id_usuario) REFERENCES usuario(id_usuario)
);

CREATE TABLE empleado (
  id_empleado BIGINT PRIMARY KEY AUTO_INCREMENT,
  id_usuario BIGINT NOT NULL,
  cargo VARCHAR(100) NULL,
  CONSTRAINT fk_empleado_usuario FOREIGN KEY (id_usuario) REFERENCES usuario(id_usuario)
);

CREATE TABLE proveedor (
  id_proveedor BIGINT PRIMARY KEY AUTO_INCREMENT,
  rut VARCHAR(15) NULL,
  nombre VARCHAR(150) NOT NULL,
  email VARCHAR(120) NULL,
  telefono VARCHAR(30) NULL,
  direccion VARCHAR(200) NULL,
  contacto VARCHAR(120) NULL,
  banco VARCHAR(80) NULL,
  tipo_cuenta VARCHAR(30) NULL,
  cuenta_bancaria VARCHAR(60) NULL
);

-- Ubicaciones
CREATE TABLE sucursal (
  id_sucursal SMALLINT PRIMARY KEY AUTO_INCREMENT,
  nombre VARCHAR(100) NOT NULL,
  direccion VARCHAR(200) NULL
);

CREATE TABLE bodega (
  id_bodega SMALLINT PRIMARY KEY AUTO_INCREMENT,
  id_sucursal SMALLINT NOT NULL,
  nombre VARCHAR(100) NOT NULL,
  CONSTRAINT fk_bodega_sucursal FOREIGN KEY (id_sucursal) REFERENCES sucursal(id_sucursal)
);

CREATE TABLE ubicacion (
  id_ubicacion INT PRIMARY KEY AUTO_INCREMENT,
  id_bodega SMALLINT NOT NULL,
  codigo VARCHAR(50) NOT NULL,
  descripcion VARCHAR(120) NULL,
  UNIQUE KEY uq_ubicacion (id_bodega, codigo),
  CONSTRAINT fk_ubicacion_bodega FOREIGN KEY (id_bodega) REFERENCES bodega(id_bodega)
);

-- Catálogo / Recetas
CREATE TABLE producto (
  id_producto BIGINT PRIMARY KEY AUTO_INCREMENT,
  sku VARCHAR(60) UNIQUE DEFAULT NULL,
  nombre VARCHAR(150) NOT NULL,
  tipo ENUM('SERVICIO','INSUMO','PRODUCTO') NOT NULL,
  unidad VARCHAR(15) NOT NULL,
  activo TINYINT(1) DEFAULT 1
);

CREATE TABLE producto_variante (
  id_variante BIGINT PRIMARY KEY AUTO_INCREMENT,
  id_producto BIGINT NOT NULL,
  codigo VARCHAR(80) NULL,
  descripcion VARCHAR(150) NULL,
  UNIQUE KEY uq_variante (id_producto, codigo),
  CONSTRAINT fk_variante_producto FOREIGN KEY (id_producto) REFERENCES producto(id_producto)
);

CREATE TABLE material (
  id_material BIGINT PRIMARY KEY AUTO_INCREMENT,
  nombre VARCHAR(120) NOT NULL,
  unidad VARCHAR(15) NOT NULL
);

CREATE TABLE receta (
  id_receta BIGINT PRIMARY KEY AUTO_INCREMENT,
  id_producto BIGINT NOT NULL,
  version SMALLINT DEFAULT 1,
  activo TINYINT(1) DEFAULT 1,
  UNIQUE KEY uq_receta (id_producto, version),
  CONSTRAINT fk_receta_producto FOREIGN KEY (id_producto) REFERENCES producto(id_producto)
);

CREATE TABLE receta_det (
  id_receta_det BIGINT PRIMARY KEY AUTO_INCREMENT,
  id_receta BIGINT NOT NULL,
  id_material BIGINT NOT NULL,
  cantidad DECIMAL(12,4) NOT NULL,
  merma_pct DECIMAL(5,2) DEFAULT 0,
  CONSTRAINT fk_receta_det_receta FOREIGN KEY (id_receta) REFERENCES receta(id_receta),
  CONSTRAINT fk_receta_det_material FOREIGN KEY (id_material) REFERENCES material(id_material)
);

-- Inventario (FIFO)
CREATE TABLE lote_stock (
  id_lote BIGINT PRIMARY KEY AUTO_INCREMENT,
  id_variante BIGINT NOT NULL,
  id_ubicacion INT NOT NULL,
  fecha_ingreso DATE NOT NULL,
  costo_unitario DECIMAL(14,4) NOT NULL,
  cantidad_inicial DECIMAL(14,4) NOT NULL,
  cantidad_disponible DECIMAL(14,4) NOT NULL,
  KEY idx_lote_var_fecha (id_variante, fecha_ingreso),
  CONSTRAINT fk_lote_variante FOREIGN KEY (id_variante) REFERENCES producto_variante(id_variante),
  CONSTRAINT fk_lote_ubic FOREIGN KEY (id_ubicacion) REFERENCES ubicacion(id_ubicacion)
);

CREATE TABLE mov_inventario (
  id_mov BIGINT PRIMARY KEY AUTO_INCREMENT,
  fecha TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  id_variante BIGINT NOT NULL,
  id_ubicacion INT NOT NULL,
  tipo ENUM('INGRESO','AJUSTE_POS','AJUSTE_NEG','SALIDA_OT','SALIDA_VENTA','TRASLADO_IN','TRASLADO_OUT') NOT NULL,
  cantidad DECIMAL(14,4) NOT NULL,
  costo_unitario DECIMAL(14,4) NULL,
  referencia_tipo VARCHAR(40) NULL,
  referencia_id BIGINT NULL,
  KEY idx_mov_var_fecha (id_variante, fecha),
  CONSTRAINT fk_mov_variante FOREIGN KEY (id_variante) REFERENCES producto_variante(id_variante),
  CONSTRAINT fk_mov_ubic FOREIGN KEY (id_ubicacion) REFERENCES ubicacion(id_ubicacion)
);

CREATE TABLE umbral_stock (
  id_umbral BIGINT PRIMARY KEY AUTO_INCREMENT,
  id_variante BIGINT NOT NULL,
  id_ubicacion INT NOT NULL,
  stock_min DECIMAL(14,4) NOT NULL,
  UNIQUE KEY uq_umbral (id_variante, id_ubicacion),
  CONSTRAINT fk_umbral_variante FOREIGN KEY (id_variante) REFERENCES producto_variante(id_variante),
  CONSTRAINT fk_umbral_ubic FOREIGN KEY (id_ubicacion) REFERENCES ubicacion(id_ubicacion)
);

-- Compras
CREATE TABLE oc (
  id_oc BIGINT PRIMARY KEY AUTO_INCREMENT,
  fecha DATE NOT NULL,
  id_proveedor BIGINT NOT NULL,
  estado ENUM('ABIERTA','RECEPCION_PARCIAL','CERRADA','ANULADA') DEFAULT 'ABIERTA',
  CONSTRAINT fk_oc_proveedor FOREIGN KEY (id_proveedor) REFERENCES proveedor(id_proveedor)
);

CREATE TABLE oc_det (
  id_oc_det BIGINT PRIMARY KEY AUTO_INCREMENT,
  id_oc BIGINT NOT NULL,
  id_variante BIGINT NOT NULL,
  cantidad DECIMAL(14,4) NOT NULL,
  precio_unitario DECIMAL(14,4) NOT NULL,
  CONSTRAINT fk_ocdet_oc FOREIGN KEY (id_oc) REFERENCES oc(id_oc),
  CONSTRAINT fk_ocdet_variante FOREIGN KEY (id_variante) REFERENCES producto_variante(id_variante)
);

CREATE TABLE recepcion (
  id_recepcion BIGINT PRIMARY KEY AUTO_INCREMENT,
  id_oc BIGINT NOT NULL,
  fecha DATE NOT NULL,
  CONSTRAINT fk_recepcion_oc FOREIGN KEY (id_oc) REFERENCES oc(id_oc)
);

CREATE TABLE recepcion_det (
  id_recepcion_det BIGINT PRIMARY KEY AUTO_INCREMENT,
  id_recepcion BIGINT NOT NULL,
  id_oc_det BIGINT NOT NULL,
  id_ubicacion INT NOT NULL,
  cantidad DECIMAL(14,4) NOT NULL,
  costo_unitario DECIMAL(14,4) NOT NULL,
  CONSTRAINT fk_recdet_recepcion FOREIGN KEY (id_recepcion) REFERENCES recepcion(id_recepcion),
  CONSTRAINT fk_recdet_ocdet FOREIGN KEY (id_oc_det) REFERENCES oc_det(id_oc_det),
  CONSTRAINT fk_recdet_ubic FOREIGN KEY (id_ubicacion) REFERENCES ubicacion(id_ubicacion)
);

-- Comercial
CREATE TABLE cotizacion (
  id_cot BIGINT PRIMARY KEY AUTO_INCREMENT,
  fecha DATE NOT NULL,
  id_cliente BIGINT NULL,
  estado ENUM('BORRADOR','ENVIADA','ACEPTADA','RECHAZADA','VENCIDA') DEFAULT 'BORRADOR',
  total DECIMAL(14,2) DEFAULT 0,
  CONSTRAINT fk_cot_cliente FOREIGN KEY (id_cliente) REFERENCES cliente(id_cliente)
);

CREATE TABLE cotizacion_det (
  id_cot_det BIGINT PRIMARY KEY AUTO_INCREMENT,
  id_cot BIGINT NOT NULL,
  id_variante BIGINT NULL,
  descripcion VARCHAR(255) NOT NULL,
  cantidad DECIMAL(14,4) NOT NULL,
  precio_unitario DECIMAL(14,4) NOT NULL,
  CONSTRAINT fk_cotdet_cot FOREIGN KEY (id_cot) REFERENCES cotizacion(id_cot),
  CONSTRAINT fk_cotdet_variante FOREIGN KEY (id_variante) REFERENCES producto_variante(id_variante)
);

CREATE TABLE pedido (
  id_pedido BIGINT PRIMARY KEY AUTO_INCREMENT,
  fecha DATE NOT NULL,
  id_cliente BIGINT NULL,
  id_cot BIGINT NULL,
  estado ENUM('ABIERTO','EN_PRODUCCION','LISTO','DESPACHADO','CERRADO','ANULADO') DEFAULT 'ABIERTO',
  total DECIMAL(14,2) DEFAULT 0,
  CONSTRAINT fk_pedido_cliente FOREIGN KEY (id_cliente) REFERENCES cliente(id_cliente),
  CONSTRAINT fk_pedido_cot FOREIGN KEY (id_cot) REFERENCES cotizacion(id_cot)
);

CREATE TABLE pedido_det (
  id_pedido_det BIGINT PRIMARY KEY AUTO_INCREMENT,
  id_pedido BIGINT NOT NULL,
  id_variante BIGINT NULL,
  descripcion VARCHAR(255) NULL,
  cantidad DECIMAL(14,4) NOT NULL,
  precio_unitario DECIMAL(14,4) NOT NULL,
  CONSTRAINT fk_peddet_pedido FOREIGN KEY (id_pedido) REFERENCES pedido(id_pedido),
  CONSTRAINT fk_peddet_variante FOREIGN KEY (id_variante) REFERENCES producto_variante(id_variante)
);

-- Producción
CREATE TABLE ot (
  id_ot BIGINT PRIMARY KEY AUTO_INCREMENT,
  id_pedido BIGINT NOT NULL,
  codigo VARCHAR(30) UNIQUE NULL,
  fecha_creacion DATE NOT NULL,
  estado ENUM('PENDIENTE','EN_PROCESO','PAUSADA','TERMINADA','ANULADA') DEFAULT 'PENDIENTE',
  prioridad TINYINT DEFAULT 3,
  CONSTRAINT fk_ot_pedido FOREIGN KEY (id_pedido) REFERENCES pedido(id_pedido)
);

CREATE TABLE ot_tarea (
  id_ot_tarea BIGINT PRIMARY KEY AUTO_INCREMENT,
  id_ot BIGINT NOT NULL,
  nombre VARCHAR(120) NOT NULL,
  estado ENUM('PENDIENTE','EN_PROCESO','TERMINADA') DEFAULT 'PENDIENTE',
  inicio DATETIME NULL,
  fin DATETIME NULL,
  responsable BIGINT NULL,
  CONSTRAINT fk_ottarea_ot FOREIGN KEY (id_ot) REFERENCES ot(id_ot),
  CONSTRAINT fk_ottarea_resp FOREIGN KEY (responsable) REFERENCES empleado(id_empleado)
);

CREATE TABLE ot_consumo_material (
  id_consumo BIGINT PRIMARY KEY AUTO_INCREMENT,
  id_ot BIGINT NOT NULL,
  id_variante BIGINT NOT NULL,
  cantidad DECIMAL(14,4) NOT NULL,
  costo_total DECIMAL(14,4) NOT NULL,
  CONSTRAINT fk_otcons_ot FOREIGN KEY (id_ot) REFERENCES ot(id_ot),
  CONSTRAINT fk_otcons_variante FOREIGN KEY (id_variante) REFERENCES producto_variante(id_variante)
);

-- Documentos / Pagos
CREATE TABLE documento_venta (
  id_doc BIGINT PRIMARY KEY AUTO_INCREMENT,
  tipo ENUM('BOLETA','FACTURA') NOT NULL,
  folio VARCHAR(30) NULL,
  fecha DATE NOT NULL,
  id_pedido BIGINT NOT NULL,
  neto DECIMAL(14,2) NOT NULL,
  iva DECIMAL(14,2) NOT NULL,
  total DECIMAL(14,2) NOT NULL,
  estado ENUM('EMITIDO','ANULADO') DEFAULT 'EMITIDO',
  CONSTRAINT fk_doc_pedido FOREIGN KEY (id_pedido) REFERENCES pedido(id_pedido)
);

CREATE TABLE pago (
  id_pago BIGINT PRIMARY KEY AUTO_INCREMENT,
  id_doc BIGINT NOT NULL,
  fecha DATETIME DEFAULT CURRENT_TIMESTAMP,
  medio ENUM('EFECTIVO','DEBITO','CREDITO','TRANSFERENCIA','MPAGO','OTRO') NOT NULL,
  monto DECIMAL(14,2) NOT NULL,
  ref_externa VARCHAR(120) NULL,
  CONSTRAINT fk_pago_doc FOREIGN KEY (id_doc) REFERENCES documento_venta(id_doc)
);

-- Envíos
CREATE TABLE envio (
  id_envio BIGINT PRIMARY KEY AUTO_INCREMENT,
  id_pedido BIGINT NOT NULL,
  carrier ENUM('BLUEEXPRESS','OTRO') NOT NULL,
  tracking VARCHAR(60) NULL,
  estado VARCHAR(40) NULL,
  creado_en TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_envio_pedido FOREIGN KEY (id_pedido) REFERENCES pedido(id_pedido)
);

CREATE TABLE envio_evento (
  id_envio_evento BIGINT PRIMARY KEY AUTO_INCREMENT,
  id_envio BIGINT NOT NULL,
  fecha DATETIME NOT NULL,
  estado VARCHAR(80) NOT NULL,
  detalle VARCHAR(255) NULL,
  CONSTRAINT fk_envioev_envio FOREIGN KEY (id_envio) REFERENCES envio(id_envio)
);

-- Archivos / Arte / Validación
CREATE TABLE archivo (
  id_archivo BIGINT PRIMARY KEY AUTO_INCREMENT,
  nombre VARCHAR(200) NOT NULL,
  mime VARCHAR(80) NULL,
  ruta VARCHAR(255) NOT NULL,
  tamano INT NULL,
  subido_por BIGINT NULL,
  creado_en TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_archivo_usuario FOREIGN KEY (subido_por) REFERENCES usuario(id_usuario)
);

CREATE TABLE arte (
  id_arte BIGINT PRIMARY KEY AUTO_INCREMENT,
  id_pedido_det BIGINT NOT NULL,
  id_archivo BIGINT NOT NULL,
  dpi INT NULL,
  ancho_mm DECIMAL(10,2) NULL,
  alto_mm DECIMAL(10,2) NULL,
  validado TINYINT(1) DEFAULT 0,
  CONSTRAINT fk_arte_peddet FOREIGN KEY (id_pedido_det) REFERENCES pedido_det(id_pedido_det),
  CONSTRAINT fk_arte_archivo FOREIGN KEY (id_archivo) REFERENCES archivo(id_archivo)
);

CREATE TABLE marca_registrada_check (
  id_check BIGINT PRIMARY KEY AUTO_INCREMENT,
  id_arte BIGINT NOT NULL,
  resultado ENUM('DESCONOCIDO','POTENCIAL_MARCA','LIBRE') DEFAULT 'DESCONOCIDO',
  fuente VARCHAR(120) NULL,
  detalle VARCHAR(255) NULL,
  creado_en TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_marca_arte FOREIGN KEY (id_arte) REFERENCES arte(id_arte)
);

-- Soporte
CREATE TABLE notificacion (
  id_notif BIGINT PRIMARY KEY AUTO_INCREMENT,
  canal ENUM('EMAIL','WHATSAPP') NOT NULL,
  destino VARCHAR(120) NOT NULL,
  asunto VARCHAR(150) NULL,
  cuerpo TEXT NULL,
  referencia_tipo VARCHAR(40) NULL,
  referencia_id BIGINT NULL,
  estado ENUM('PENDIENTE','ENVIADA','ERROR') DEFAULT 'PENDIENTE',
  creado_en TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE audit_log (
  id_audit BIGINT PRIMARY KEY AUTO_INCREMENT,
  entidad VARCHAR(60) NOT NULL,
  id_entidad BIGINT NOT NULL,
  accion ENUM('INSERT','UPDATE','DELETE') NOT NULL,
  usuario BIGINT NULL,
  fecha TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  detalle JSON NULL,
  CONSTRAINT fk_audit_usuario FOREIGN KEY (usuario) REFERENCES usuario(id_usuario)
);

CREATE TABLE qr (
  id_qr BIGINT PRIMARY KEY AUTO_INCREMENT,
  entidad VARCHAR(40) NOT NULL,
  id_entidad BIGINT NOT NULL,
  payload JSON NOT NULL,
  creado_en TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uq_qr (entidad, id_entidad)
);

CREATE TABLE parametro (
  clave VARCHAR(80) PRIMARY KEY,
  valor VARCHAR(255) NOT NULL
);

-- Datos base
INSERT INTO rol (nombre) VALUES ('ADMIN'),('EMPLEADO'),('CLIENTE');
INSERT INTO usuario (email, hash_password, nombre) VALUES ('admin@kingston.cl', '$2y$10$abcdefghijklmnopqrstuvABCDEFGHijklmnopqrstu/abcdefghi', 'Administrador');
INSERT INTO usuario_rol (id_usuario, id_rol) VALUES (1, 1);

-- Proveedores desde Excel
INSERT INTO proveedor (nombre) VALUES ('INNOPAPER');
INSERT INTO proveedor (nombre) VALUES ('NONE');
INSERT INTO proveedor (nombre) VALUES ('SWIN');

-- Productos desde Excel (unidad = 'm', tipo = 'INSUMO')
INSERT INTO producto (sku, nombre, tipo, unidad) VALUES ('VINILO_TEXTIL_PU_CAMEL_INNOPAPER', 'VINILO TEXTIL PU CAMEL INNOPAPER', 'INSUMO', 'm');
INSERT INTO producto (sku, nombre, tipo, unidad) VALUES ('VINILO_TEXTIL_PU_APPLE_GREEN_INNOPAPER', 'VINILO TEXTIL PU APPLE GREEN INNOPAPER', 'INSUMO', 'm');
INSERT INTO producto (sku, nombre, tipo, unidad) VALUES ('VINILO_TEXTIL_PU_AQUA_INNOPAPER', 'VINILO TEXTIL PU AQUA INNOPAPER', 'INSUMO', 'm');
INSERT INTO producto (sku, nombre, tipo, unidad) VALUES ('VINILO_TEXTIL_PU_BEIGE_INNOPAPER', 'VINILO TEXTIL PU BEIGE INNOPAPER', 'INSUMO', 'm');
INSERT INTO producto (sku, nombre, tipo, unidad) VALUES ('VINILO_TEXTIL_PU_BLACK_INNOPAPER', 'VINILO TEXTIL PU BLACK INNOPAPER', 'INSUMO', 'm');
INSERT INTO producto (sku, nombre, tipo, unidad) VALUES ('VINILO_TEXTIL_PU_BLUE_INNOPAPER', 'VINILO TEXTIL PU BLUE INNOPAPER', 'INSUMO', 'm');
INSERT INTO producto (sku, nombre, tipo, unidad) VALUES ('VINILO_TEXTIL_PU_BROWN_INNOPAPER', 'VINILO TEXTIL PU BROWN INNOPAPER', 'INSUMO', 'm');
INSERT INTO producto (sku, nombre, tipo, unidad) VALUES ('VINILO_TEXTIL_PU_DARK_AQUA_INNOPAPER', 'VINILO TEXTIL PU DARK AQUA INNOPAPER', 'INSUMO', 'm');
INSERT INTO producto (sku, nombre, tipo, unidad) VALUES ('VINILO_TEXTIL_PU_DARK_GREEN_INNOPAPER', 'VINILO TEXTIL PU DARK GREEN INNOPAPER', 'INSUMO', 'm');
INSERT INTO producto (sku, nombre, tipo, unidad) VALUES ('VINILO_TEXTIL_PU_DARK_PINK_INNOPAPER', 'VINILO TEXTIL PU DARK PINK INNOPAPER', 'INSUMO', 'm');
INSERT INTO producto (sku, nombre, tipo, unidad) VALUES ('VINILO_TEXTIL_PU_DARK_PURPLE_INNOPAPER', 'VINILO TEXTIL PU DARK PURPLE INNOPAPER', 'INSUMO', 'm');
INSERT INTO producto (sku, nombre, tipo, unidad) VALUES ('VINILO_TEXTIL_PU_FUCHSIA_INNOPAPER', 'VINILO TEXTIL PU FUCHSIA INNOPAPER', 'INSUMO', 'm');
INSERT INTO producto (sku, nombre, tipo, unidad) VALUES ('VINILO_TEXTIL_PU_GOLD_INNOPAPER', 'VINILO TEXTIL PU GOLD INNOPAPER', 'INSUMO', 'm');
INSERT INTO producto (sku, nombre, tipo, unidad) VALUES ('VINILO_TEXTIL_PU_GOLDEN_YELLOW_INNOPAPER', 'VINILO TEXTIL PU GOLDEN YELLOW INNOPAPER', 'INSUMO', 'm');
INSERT INTO producto (sku, nombre, tipo, unidad) VALUES ('VINILO_TEXTIL_PU_GRAY_INNOPAPER', 'VINILO TEXTIL PU GRAY INNOPAPER', 'INSUMO', 'm');
INSERT INTO producto (sku, nombre, tipo, unidad) VALUES ('VINILO_TEXTIL_PU_GREEN_INNOPAPER', 'VINILO TEXTIL PU GREEN INNOPAPER', 'INSUMO', 'm');
INSERT INTO producto (sku, nombre, tipo, unidad) VALUES ('VINILO_TEXTIL_PU_LEMON_YELLOW_INNOPAPER', 'VINILO TEXTIL PU LEMON YELLOW INNOPAPER', 'INSUMO', 'm');
INSERT INTO producto (sku, nombre, tipo, unidad) VALUES ('VINILO_TEXTIL_PU_LIGHT_BLUE_INNOPAPER', 'VINILO TEXTIL PU LIGHT BLUE INNOPAPER', 'INSUMO', 'm');
INSERT INTO producto (sku, nombre, tipo, unidad) VALUES ('VINILO_TEXTIL_PU_LIGHT_BROWN_INNOPAPER', 'VINILO TEXTIL PU LIGHT BROWN INNOPAPER', 'INSUMO', 'm');
INSERT INTO producto (sku, nombre, tipo, unidad) VALUES ('VINILO_TEXTIL_PU_LIGHT_GREEN_INNOPAPER', 'VINILO TEXTIL PU LIGHT GREEN INNOPAPER', 'INSUMO', 'm');
INSERT INTO producto (sku, nombre, tipo, unidad) VALUES ('VINILO_TEXTIL_PU_LIGHT_PINK_INNOPAPER', 'VINILO TEXTIL PU LIGHT PINK INNOPAPER', 'INSUMO', 'm');
INSERT INTO producto (sku, nombre, tipo, unidad) VALUES ('VINILO_TEXTIL_PU_MAROON_INNOPAPER', 'VINILO TEXTIL PU MAROON INNOPAPER', 'INSUMO', 'm');
INSERT INTO producto (sku, nombre, tipo, unidad) VALUES ('VINILO_TEXTIL_PU_NAVY_INNOPAPER', 'VINILO TEXTIL PU NAVY INNOPAPER', 'INSUMO', 'm');
INSERT INTO producto (sku, nombre, tipo, unidad) VALUES ('VINILO_TEXTIL_PU_NEON_BLUE_INNOPAPER', 'VINILO TEXTIL PU NEON BLUE INNOPAPER', 'INSUMO', 'm');
INSERT INTO producto (sku, nombre, tipo, unidad) VALUES ('VINILO_TEXTIL_PU_NEON_ORANGE_INNOPAPER', 'VINILO TEXTIL PU NEON ORANGE INNOPAPER', 'INSUMO', 'm');
INSERT INTO producto (sku, nombre, tipo, unidad) VALUES ('VINILO_TEXTIL_PU_NEON_PINK_INNOPAPER', 'VINILO TEXTIL PU NEON PINK INNOPAPER', 'INSUMO', 'm');
INSERT INTO producto (sku, nombre, tipo, unidad) VALUES ('VINILO_TEXTIL_PU_NEON_YELLOW_INNOPAPER', 'VINILO TEXTIL PU NEON YELLOW INNOPAPER', 'INSUMO', 'm');
INSERT INTO producto (sku, nombre, tipo, unidad) VALUES ('VINILO_TEXTIL_PU_ORANGE_INNOPAPER', 'VINILO TEXTIL PU ORANGE INNOPAPER', 'INSUMO', 'm');
INSERT INTO producto (sku, nombre, tipo, unidad) VALUES ('VINILO_TEXTIL_PU_PASTEL_BLUE_INNOPAPER', 'VINILO TEXTIL PU PASTEL BLUE INNOPAPER', 'INSUMO', 'm');
INSERT INTO producto (sku, nombre, tipo, unidad) VALUES ('VINILO_TEXTIL_PU_PASTEL_GRASS_INNOPAPER', 'VINILO TEXTIL PU PASTEL GRASS INNOPAPER', 'INSUMO', 'm');
INSERT INTO producto (sku, nombre, tipo, unidad) VALUES ('VINILO_TEXTIL_PU_PASTEL_JADE_INNOPAPER', 'VINILO TEXTIL PU PASTEL JADE INNOPAPER', 'INSUMO', 'm');
INSERT INTO producto (sku, nombre, tipo, unidad) VALUES ('VINILO_TEXTIL_PU_PASTEL_LIGHT_GREEN_INNOPAPER', 'VINILO TEXTIL PU PASTEL LIGHT GREEN INNOPAPER', 'INSUMO', 'm');
INSERT INTO producto (sku, nombre, tipo, unidad) VALUES ('VINILO_TEXTIL_PU_PASTEL_PINK_INNOPAPER', 'VINILO TEXTIL PU PASTEL PINK INNOPAPER', 'INSUMO', 'm');
INSERT INTO producto (sku, nombre, tipo, unidad) VALUES ('VINILO_TEXTIL_PU_PASTEL_PURPLE_INNOPAPER', 'VINILO TEXTIL PU PASTEL PURPLE INNOPAPER', 'INSUMO', 'm');
INSERT INTO producto (sku, nombre, tipo, unidad) VALUES ('VINILO_TEXTIL_PU_PASTEL_SALMON_INNOPAPER', 'VINILO TEXTIL PU PASTEL SALMON INNOPAPER', 'INSUMO', 'm');
INSERT INTO producto (sku, nombre, tipo, unidad) VALUES ('VINILO_TEXTIL_PU_PINK_INNOPAPER', 'VINILO TEXTIL PU PINK INNOPAPER', 'INSUMO', 'm');
INSERT INTO producto (sku, nombre, tipo, unidad) VALUES ('VINILO_TEXTIL_PU_PURPLE_INNOPAPER', 'VINILO TEXTIL PU PURPLE INNOPAPER', 'INSUMO', 'm');
INSERT INTO producto (sku, nombre, tipo, unidad) VALUES ('VINILO_TEXTIL_PU_RED_INNOPAPER', 'VINILO TEXTIL PU RED INNOPAPER', 'INSUMO', 'm');
INSERT INTO producto (sku, nombre, tipo, unidad) VALUES ('VINILO_TEXTIL_PU_ROSE_GOLD_INNOPAPER', 'VINILO TEXTIL PU ROSE GOLD INNOPAPER', 'INSUMO', 'm');
INSERT INTO producto (sku, nombre, tipo, unidad) VALUES ('VINILO_TEXTIL_PU_ROYAL_BLUE_INNOPAPER', 'VINILO TEXTIL PU ROYAL BLUE INNOPAPER', 'INSUMO', 'm');
INSERT INTO producto (sku, nombre, tipo, unidad) VALUES ('VINILO_TEXTIL_PU_SILVER_INNOPAPER', 'VINILO TEXTIL PU SILVER INNOPAPER', 'INSUMO', 'm');
INSERT INTO producto (sku, nombre, tipo, unidad) VALUES ('VINILO_TEXTIL_PU_SKY_BLUE-1_INNOPAPER', 'VINILO TEXTIL PU SKY BLUE-1 INNOPAPER', 'INSUMO', 'm');
INSERT INTO producto (sku, nombre, tipo, unidad) VALUES ('VINILO_TEXTIL_PU_SKY_BLUE-2_INNOPAPER', 'VINILO TEXTIL PU SKY BLUE-2 INNOPAPER', 'INSUMO', 'm');
INSERT INTO producto (sku, nombre, tipo, unidad) VALUES ('VINILO_TEXTIL_PU_SUN_RED_INNOPAPER', 'VINILO TEXTIL PU SUN RED INNOPAPER', 'INSUMO', 'm');
INSERT INTO producto (sku, nombre, tipo, unidad) VALUES ('VINILO_TEXTIL_PU_SUN_YELLOW_INNOPAPER', 'VINILO TEXTIL PU SUN YELLOW INNOPAPER', 'INSUMO', 'm');
INSERT INTO producto (sku, nombre, tipo, unidad) VALUES ('VINILO_TEXTIL_PU_VIOLET_INNOPAPER', 'VINILO TEXTIL PU VIOLET INNOPAPER', 'INSUMO', 'm');
INSERT INTO producto (sku, nombre, tipo, unidad) VALUES ('VINILO_TEXTIL_PU_WHITE_INNOPAPER', 'VINILO TEXTIL PU WHITE INNOPAPER', 'INSUMO', 'm');
INSERT INTO producto (sku, nombre, tipo, unidad) VALUES ('VINILO_TEXTIL_PU_YELLOW_INNOPAPER', 'VINILO TEXTIL PU YELLOW INNOPAPER', 'INSUMO', 'm');
INSERT INTO producto (sku, nombre, tipo, unidad) VALUES ('VINILO_TEXTIL_PUFF_BLACK_SWIN', 'VINILO TEXTIL PUFF BLACK SWIN', 'INSUMO', 'm');
INSERT INTO producto (sku, nombre, tipo, unidad) VALUES ('VINILO_TEXTIL_PUFF_WHITE_SWIN', 'VINILO TEXTIL PUFF WHITE SWIN', 'INSUMO', 'm');
INSERT INTO producto (sku, nombre, tipo, unidad) VALUES ('VINILO_TEXTIL_PUFF_YELLOW_SWIN', 'VINILO TEXTIL PUFF YELLOW SWIN', 'INSUMO', 'm');
INSERT INTO producto (sku, nombre, tipo, unidad) VALUES ('VINILO_TEXTIL_PUFF_NEON_PINK_SWIN', 'VINILO TEXTIL PUFF NEON PINK SWIN', 'INSUMO', 'm');
INSERT INTO producto (sku, nombre, tipo, unidad) VALUES ('VINILO_TEXTIL_PUFF_GRAY_SWIN', 'VINILO TEXTIL PUFF GRAY SWIN', 'INSUMO', 'm');
INSERT INTO producto (sku, nombre, tipo, unidad) VALUES ('VINILO_TEXTIL_PUFF_GOLD_SWIN', 'VINILO TEXTIL PUFF GOLD SWIN', 'INSUMO', 'm');
INSERT INTO producto (sku, nombre, tipo, unidad) VALUES ('VINILO_TEXTIL_PUFF_SILVER_SWIN', 'VINILO TEXTIL PUFF SILVER SWIN', 'INSUMO', 'm');
INSERT INTO producto (sku, nombre, tipo, unidad) VALUES ('VINILO_TEXTIL_PUFF_NEON_BLUE_SWIN', 'VINILO TEXTIL PUFF NEON BLUE SWIN', 'INSUMO', 'm');
INSERT INTO producto (sku, nombre, tipo, unidad) VALUES ('VINILO_TEXTIL_PUFF_ROYAL_BLUE_SWIN', 'VINILO TEXTIL PUFF ROYAL BLUE SWIN', 'INSUMO', 'm');
INSERT INTO producto (sku, nombre, tipo, unidad) VALUES ('VINILO_TEXTIL_PUFF_NEON_YELLOW_SWIN', 'VINILO TEXTIL PUFF NEON YELLOW SWIN', 'INSUMO', 'm');
INSERT INTO producto (sku, nombre, tipo, unidad) VALUES ('VINILO_TEXTIL_PUFF_NEON_ORANGE_SWIN', 'VINILO TEXTIL PUFF NEON ORANGE SWIN', 'INSUMO', 'm');
INSERT INTO producto (sku, nombre, tipo, unidad) VALUES ('VINILO_TEXTIL_PUFF_CELESTELIGHT_BLUE_SWIN', 'VINILO TEXTIL PUFF CELESTE/LIGHT BLUE SWIN', 'INSUMO', 'm');
INSERT INTO producto (sku, nombre, tipo, unidad) VALUES ('VINILO_TEXTIL_PUFF_TURQUOISE_SWIN', 'VINILO TEXTIL PUFF TURQUOISE SWIN', 'INSUMO', 'm');
INSERT INTO producto (sku, nombre, tipo, unidad) VALUES ('VINILO_TEXTIL_PUFF_BEIGE_SWIN', 'VINILO TEXTIL PUFF BEIGE SWIN', 'INSUMO', 'm');
INSERT INTO producto (sku, nombre, tipo, unidad) VALUES ('VINILO_TEXTIL_PUFF_PASTEL_BLUE_SWIN', 'VINILO TEXTIL PUFF PASTEL BLUE SWIN', 'INSUMO', 'm');
INSERT INTO producto (sku, nombre, tipo, unidad) VALUES ('VINILO_TEXTIL_PUFF_NEON_PINK_INNOPAPER', 'VINILO TEXTIL PUFF NEON PINK INNOPAPER', 'INSUMO', 'm');
INSERT INTO producto (sku, nombre, tipo, unidad) VALUES ('VINILO_TEXTIL_PUFF_BLACK_INNOPAPER', 'VINILO TEXTIL PUFF BLACK INNOPAPER', 'INSUMO', 'm');
INSERT INTO producto (sku, nombre, tipo, unidad) VALUES ('VINILO_TEXTIL_PUFF_WHITE_INNOPAPER', 'VINILO TEXTIL PUFF WHITE INNOPAPER', 'INSUMO', 'm');
INSERT INTO producto (sku, nombre, tipo, unidad) VALUES ('VINILO_TEXTIL_PUFF_NEON_GREEN_INNOPAPER', 'VINILO TEXTIL PUFF NEON GREEN INNOPAPER', 'INSUMO', 'm');
INSERT INTO producto (sku, nombre, tipo, unidad) VALUES ('VINILO_TEXTIL_PUFF_RED_INNOPAPER', 'VINILO TEXTIL PUFF RED INNOPAPER', 'INSUMO', 'm');
INSERT INTO producto (sku, nombre, tipo, unidad) VALUES ('VINILO_TEXTIL_PUFF_LILAC_INNOPAPER', 'VINILO TEXTIL PUFF LILAC INNOPAPER', 'INSUMO', 'm');
INSERT INTO producto (sku, nombre, tipo, unidad) VALUES ('VINILO_TEXTIL_EMBOCHARMELEON_ROYAL_BLUE_SWIN', 'VINILO TEXTIL EMBOCHARMELEON ROYAL BLUE SWIN', 'INSUMO', 'm');
INSERT INTO producto (sku, nombre, tipo, unidad) VALUES ('VINILO_TEXTIL_EMBOCHARMELEON_SILVER_SWIN', 'VINILO TEXTIL EMBOCHARMELEON SILVER SWIN', 'INSUMO', 'm');
INSERT INTO producto (sku, nombre, tipo, unidad) VALUES ('VINILO_TEXTIL_EMBOCHARMELEON_GOLD_SWIN', 'VINILO TEXTIL EMBOCHARMELEON GOLD SWIN', 'INSUMO', 'm');
INSERT INTO producto (sku, nombre, tipo, unidad) VALUES ('VINILO_TEXTIL_EMBOCHARMELEON_PINK_SWIN', 'VINILO TEXTIL EMBOCHARMELEON PINK SWIN', 'INSUMO', 'm');
INSERT INTO producto (sku, nombre, tipo, unidad) VALUES ('VINILO_TEXTIL_EMBOCHARMELEON_BLACK_SWIN', 'VINILO TEXTIL EMBOCHARMELEON BLACK SWIN', 'INSUMO', 'm');
INSERT INTO producto (sku, nombre, tipo, unidad) VALUES ('VINILO_TEXTIL_EMBOCHARMELEON_RED_SWIN', 'VINILO TEXTIL EMBOCHARMELEON RED SWIN', 'INSUMO', 'm');
INSERT INTO producto (sku, nombre, tipo, unidad) VALUES ('VINILO_TEXTIL_SILICONE_3D_NEON_RED_INNOPAPER', 'VINILO TEXTIL SILICONE 3D NEON RED INNOPAPER', 'INSUMO', 'm');
INSERT INTO producto (sku, nombre, tipo, unidad) VALUES ('VINILO_TEXTIL_SILICONE_3D_YELLOW_INNOPAPER', 'VINILO TEXTIL SILICONE 3D YELLOW INNOPAPER', 'INSUMO', 'm');
INSERT INTO producto (sku, nombre, tipo, unidad) VALUES ('VINILO_TEXTIL_SILICONE_3D_NEON_YELLOW_INNOPAPER', 'VINILO TEXTIL SILICONE 3D NEON YELLOW INNOPAPER', 'INSUMO', 'm');
INSERT INTO producto (sku, nombre, tipo, unidad) VALUES ('VINILO_TEXTIL_SILICONE_3D_RED_INNOPAPER', 'VINILO TEXTIL SILICONE 3D RED INNOPAPER', 'INSUMO', 'm');
INSERT INTO producto (sku, nombre, tipo, unidad) VALUES ('VINILO_TEXTIL_PRINTABLE_PU_WHITE_INNOPAPER', 'VINILO TEXTIL PRINTABLE PU WHITE INNOPAPER', 'INSUMO', 'm');
INSERT INTO producto (sku, nombre, tipo, unidad) VALUES ('VINILO_TEXTIL_PRINTABLE_PVC_WHITE_INNOPAPER', 'VINILO TEXTIL PRINTABLE PVC WHITE INNOPAPER', 'INSUMO', 'm');
INSERT INTO producto (sku, nombre, tipo, unidad) VALUES ('VINILO_TEXTIL_PVC_SPV-14_MAGENTA_SWIN', 'VINILO TEXTIL PVC SPV-14 MAGENTA SWIN', 'INSUMO', 'm');
INSERT INTO producto (sku, nombre, tipo, unidad) VALUES ('VINILO_TEXTIL_PVC_SPV-34_LILAC_SWIN', 'VINILO TEXTIL PVC SPV-34 LILAC SWIN', 'INSUMO', 'm');
INSERT INTO producto (sku, nombre, tipo, unidad) VALUES ('VINILO_TEXTIL_PVC_SPV-35_TURQUOISE_SWIN', 'VINILO TEXTIL PVC SPV-35 TURQUOISE SWIN', 'INSUMO', 'm');
INSERT INTO producto (sku, nombre, tipo, unidad) VALUES ('VINILO_TEXTIL_PVC_SPV-33_AQUAMARINE_SWIN', 'VINILO TEXTIL PVC SPV-33 AQUAMARINE SWIN', 'INSUMO', 'm');
INSERT INTO producto (sku, nombre, tipo, unidad) VALUES ('VINILO_TEXTIL_PVC_SPV-20_GOLD_SWIN', 'VINILO TEXTIL PVC SPV-20 GOLD SWIN', 'INSUMO', 'm');
INSERT INTO producto (sku, nombre, tipo, unidad) VALUES ('VINILO_TEXTIL_PVC_SPV-05_SBLUE_SWIN', 'VINILO TEXTIL PVC SPV-05 S/BLUE SWIN', 'INSUMO', 'm');
INSERT INTO producto (sku, nombre, tipo, unidad) VALUES ('VINILO_TEXTIL_PVC_SPV-09_LYELLOW_SWIN', 'VINILO TEXTIL PVC SPV-09 L/YELLOW SWIN', 'INSUMO', 'm');
INSERT INTO producto (sku, nombre, tipo, unidad) VALUES ('VINILO_TEXTIL_PVC_SPV-06_MBLUE_SWIN', 'VINILO TEXTIL PVC SPV-06 M/BLUE SWIN', 'INSUMO', 'm');
INSERT INTO producto (sku, nombre, tipo, unidad) VALUES ('VINILO_TEXTIL_PVC_SPV-07_ROYAL_BLUE_SWIN', 'VINILO TEXTIL PVC SPV-07 ROYAL BLUE SWIN', 'INSUMO', 'm');
INSERT INTO producto (sku, nombre, tipo, unidad) VALUES ('VINILO_DECORATIVO_DECORATIVO_CINTA_DE_TRASPASO_SWIN', 'VINILO DECORATIVO DECORATIVO CINTA DE TRASPASO SWIN', 'INSUMO', 'm');
INSERT INTO producto (sku, nombre, tipo, unidad) VALUES ('VINILO_TEXTIL_METAL_FABRIC_GREEN_INNOPAPER', 'VINILO TEXTIL METAL FABRIC GREEN INNOPAPER', 'INSUMO', 'm');
INSERT INTO producto (sku, nombre, tipo, unidad) VALUES ('VINILO_TEXTIL_METAL_FABRIC_BLACK_INNOPAPER', 'VINILO TEXTIL METAL FABRIC BLACK INNOPAPER', 'INSUMO', 'm');
INSERT INTO producto (sku, nombre, tipo, unidad) VALUES ('VINILO_TEXTIL_METAL_FABRIC_RED_INNOPAPER', 'VINILO TEXTIL METAL FABRIC RED INNOPAPER', 'INSUMO', 'm');
INSERT INTO producto (sku, nombre, tipo, unidad) VALUES ('VINILO_TEXTIL_METAL_FABRIC_GOLD_INNOPAPER', 'VINILO TEXTIL METAL FABRIC GOLD INNOPAPER', 'INSUMO', 'm');
INSERT INTO producto (sku, nombre, tipo, unidad) VALUES ('VINILO_TEXTIL_METAL_FABRIC_SILVER_INNOPAPER', 'VINILO TEXTIL METAL FABRIC SILVER INNOPAPER', 'INSUMO', 'm');
INSERT INTO producto (sku, nombre, tipo, unidad) VALUES ('VINILO_TEXTIL_SUBLIFABRIC_WHITE_INNOPAPER', 'VINILO TEXTIL SUBLIFABRIC WHITE INNOPAPER', 'INSUMO', 'm');
INSERT INTO producto (sku, nombre, tipo, unidad) VALUES ('VINILO_TEXTIL_SUBLIFLOCK_WHITE_INNOPAPER', 'VINILO TEXTIL SUBLIFLOCK WHITE INNOPAPER', 'INSUMO', 'm');
INSERT INTO producto (sku, nombre, tipo, unidad) VALUES ('VINILO_TEXTIL_SUBLIBORDADO_WHITE_INNOPAPER', 'VINILO TEXTIL SUBLIBORDADO WHITE INNOPAPER', 'INSUMO', 'm');
INSERT INTO producto (sku, nombre, tipo, unidad) VALUES ('VINILO_TEXTIL_REFLECTIVE_WHITE_INNOPAPER', 'VINILO TEXTIL REFLECTIVE WHITE INNOPAPER', 'INSUMO', 'm');
INSERT INTO producto (sku, nombre, tipo, unidad) VALUES ('VINILO_TEXTIL_MASKING_FILM_FOR_PRINTABLE_NONE_INNOPAPER', 'VINILO TEXTIL MASKING FILM FOR PRINTABLE NONE INNOPAPER', 'INSUMO', 'm');
INSERT INTO producto (sku, nombre, tipo, unidad) VALUES ('VINILO_TEXTIL_BRICK_SBR-02-BLACK_SWIN', 'VINILO TEXTIL BRICK SBR-02-BLACK SWIN', 'INSUMO', 'm');
INSERT INTO producto (sku, nombre, tipo, unidad) VALUES ('VINILO_TEXTIL_BRICK_SBR-WHITE_SWIN', 'VINILO TEXTIL BRICK SBR-WHITE SWIN', 'INSUMO', 'm');
INSERT INTO producto (sku, nombre, tipo, unidad) VALUES ('VINILO_TEXTIL_BRICK_SBR-04-SILVER_SWIN', 'VINILO TEXTIL BRICK SBR-04-SILVER SWIN', 'INSUMO', 'm');
INSERT INTO producto (sku, nombre, tipo, unidad) VALUES ('VINILO_TEXTIL_BRICK_SBR-03-GOLD_SWIN', 'VINILO TEXTIL BRICK SBR-03-GOLD SWIN', 'INSUMO', 'm');
INSERT INTO producto (sku, nombre, tipo, unidad) VALUES ('VINILO_TEXTIL_BRICK_SBR-11-YELLOW_SWIN', 'VINILO TEXTIL BRICK SBR-11-YELLOW SWIN', 'INSUMO', 'm');
INSERT INTO producto (sku, nombre, tipo, unidad) VALUES ('VINILO_TEXTIL_BRICK_SBR-08-SKY_BLUE_SWIN', 'VINILO TEXTIL BRICK SBR-08-SKY BLUE SWIN', 'INSUMO', 'm');
INSERT INTO producto (sku, nombre, tipo, unidad) VALUES ('VINILO_TEXTIL_GLITTER_SGL-16-PINK_SWIN', 'VINILO TEXTIL GLITTER SGL-16-PINK SWIN', 'INSUMO', 'm');
INSERT INTO producto (sku, nombre, tipo, unidad) VALUES ('VINILO_TEXTIL_GLITTER_SGL-38_RAINBOW_SWIN', 'VINILO TEXTIL GLITTER SGL-38 RAINBOW SWIN', 'INSUMO', 'm');
INSERT INTO producto (sku, nombre, tipo, unidad) VALUES ('VINILO_TEXTIL_GLITTER_SGL-15_ROYAL_BLUE_SWIN', 'VINILO TEXTIL GLITTER SGL-15 ROYAL BLUE SWIN', 'INSUMO', 'm');
INSERT INTO producto (sku, nombre, tipo, unidad) VALUES ('VINILO_TEXTIL_GLITTER_SGL-55_PASTEL_PINK_SWIN', 'VINILO TEXTIL GLITTER SGL-55 PASTEL PINK SWIN', 'INSUMO', 'm');
INSERT INTO producto (sku, nombre, tipo, unidad) VALUES ('VINILO_TEXTIL_GLITTER_SGL-01_SILVER_SWIN', 'VINILO TEXTIL GLITTER SGL-01 SILVER SWIN', 'INSUMO', 'm');
INSERT INTO producto (sku, nombre, tipo, unidad) VALUES ('VINILO_TEXTIL_GLITTER_SGL-29_VIOLET_SWIN', 'VINILO TEXTIL GLITTER SGL-29 VIOLET SWIN', 'INSUMO', 'm');
INSERT INTO producto (sku, nombre, tipo, unidad) VALUES ('VINILO_TEXTIL_GLITTER_SGL-10_SKY_BLUE_SWIN', 'VINILO TEXTIL GLITTER SGL-10 SKY BLUE SWIN', 'INSUMO', 'm');
INSERT INTO producto (sku, nombre, tipo, unidad) VALUES ('VINILO_TEXTIL_GLITTER_SGL-04_LIGHT_GOLD_SWIN', 'VINILO TEXTIL GLITTER SGL-04 LIGHT GOLD SWIN', 'INSUMO', 'm');
INSERT INTO producto (sku, nombre, tipo, unidad) VALUES ('VINILO_TEXTIL_GLITTER_SGL-09_BLACK_SWIN', 'VINILO TEXTIL GLITTER SGL-09 BLACK SWIN', 'INSUMO', 'm');
INSERT INTO producto (sku, nombre, tipo, unidad) VALUES ('VINILO_TEXTIL_GLITTER_SGL-32_AQUA_SWIN', 'VINILO TEXTIL GLITTER SGL-32 AQUA SWIN', 'INSUMO', 'm');
INSERT INTO producto (sku, nombre, tipo, unidad) VALUES ('VINILO_TEXTIL_GLITTER_SGL-03_RED_SWIN', 'VINILO TEXTIL GLITTER SGL-03 RED SWIN', 'INSUMO', 'm');
INSERT INTO producto (sku, nombre, tipo, unidad) VALUES ('VINILO_TEXTIL_GLITTER_BLACK_INNOPAPER', 'VINILO TEXTIL GLITTER BLACK INNOPAPER', 'INSUMO', 'm');
INSERT INTO producto (sku, nombre, tipo, unidad) VALUES ('VINILO_TEXTIL_GLITTER_MARRON_INNOPAPER', 'VINILO TEXTIL GLITTER MARRON INNOPAPER', 'INSUMO', 'm');
INSERT INTO producto (sku, nombre, tipo, unidad) VALUES ('VINILO_TEXTIL_FLOCK_SFL-04_NAVY_SWIN', 'VINILO TEXTIL FLOCK SFL-04 NAVY SWIN', 'INSUMO', 'm');
INSERT INTO producto (sku, nombre, tipo, unidad) VALUES ('VINILO_TEXTIL_FLOCK_SFL-01_WHITE_SWIN', 'VINILO TEXTIL FLOCK SFL-01 WHITE SWIN', 'INSUMO', 'm');
INSERT INTO producto (sku, nombre, tipo, unidad) VALUES ('VINILO_TEXTIL_FLOCK_SFL-10_BLACK_SWIN', 'VINILO TEXTIL FLOCK SFL-10 BLACK SWIN', 'INSUMO', 'm');
INSERT INTO producto (sku, nombre, tipo, unidad) VALUES ('VINILO_TEXTIL_FLOCK_SFL-05_RED_SWIN', 'VINILO TEXTIL FLOCK SFL-05 RED SWIN', 'INSUMO', 'm');
INSERT INTO producto (sku, nombre, tipo, unidad) VALUES ('VINILO_TEXTIL_FLOCK_SFL-06_BLUE_SWIN', 'VINILO TEXTIL FLOCK SFL-06 BLUE SWIN', 'INSUMO', 'm');
INSERT INTO producto (sku, nombre, tipo, unidad) VALUES ('VINILO_TEXTIL_FLOCK_SFL-20_GYELLOW_SWIN', 'VINILO TEXTIL FLOCK SFL-20 G/YELLOW SWIN', 'INSUMO', 'm');
INSERT INTO producto (sku, nombre, tipo, unidad) VALUES ('VINILO_TEXTIL_FLOCK_SFL-12_ORANGE_SWIN', 'VINILO TEXTIL FLOCK SFL-12 ORANGE SWIN', 'INSUMO', 'm');
INSERT INTO producto (sku, nombre, tipo, unidad) VALUES ('VINILO_TEXTIL_FLOCK_SFL-16_PINK_SWIN', 'VINILO TEXTIL FLOCK SFL-16 PINK SWIN', 'INSUMO', 'm');
INSERT INTO producto (sku, nombre, tipo, unidad) VALUES ('VINILO_TEXTIL_FLOCK_SFL-03_PINK_SWIN', 'VINILO TEXTIL FLOCK SFL-03 PINK SWIN', 'INSUMO', 'm');
INSERT INTO producto (sku, nombre, tipo, unidad) VALUES ('VINILO_TEXTIL_PU_INYECTABLE_PRINTABLE_SWIN', 'VINILO TEXTIL PU INYECTABLE PRINTABLE SWIN', 'INSUMO', 'm');
INSERT INTO producto (sku, nombre, tipo, unidad) VALUES ('VINILO_TEXTIL_PU_SPU-26PINK_SWIN', 'VINILO TEXTIL PU SPU-26/PINK SWIN', 'INSUMO', 'm');
INSERT INTO producto (sku, nombre, tipo, unidad) VALUES ('VINILO_TEXTIL_PU_SPU-15_DGREY_SWIN', 'VINILO TEXTIL PU SPU-15 D/GREY SWIN', 'INSUMO', 'm');
INSERT INTO producto (sku, nombre, tipo, unidad) VALUES ('VINILO_TEXTIL_PU_SPU-53_DBROWN_SWIN', 'VINILO TEXTIL PU SPU-53 D/BROWN SWIN', 'INSUMO', 'm');
INSERT INTO producto (sku, nombre, tipo, unidad) VALUES ('VINILO_TEXTIL_PU_SPU-06_MBLUE_SWIN', 'VINILO TEXTIL PU SPU-06 M/BLUE SWIN', 'INSUMO', 'm');
INSERT INTO producto (sku, nombre, tipo, unidad) VALUES ('VINILO_TEXTIL_PU_SPU-52_BPINK_SWIN', 'VINILO TEXTIL PU SPU-52 B/PINK SWIN', 'INSUMO', 'm');
INSERT INTO producto (sku, nombre, tipo, unidad) VALUES ('VINILO_TEXTIL_PU_SPU-48_CORAL_SWIN', 'VINILO TEXTIL PU SPU-48 CORAL SWIN', 'INSUMO', 'm');
INSERT INTO producto (sku, nombre, tipo, unidad) VALUES ('VINILO_TEXTIL_PU_SPU-18_BURGUNDY_SWIN', 'VINILO TEXTIL PU SPU-18 BURGUNDY SWIN', 'INSUMO', 'm');
INSERT INTO producto (sku, nombre, tipo, unidad) VALUES ('VINILO_TEXTIL_FOIL_BUBBLE_GOLD_INNOPAPER', 'VINILO TEXTIL FOIL BUBBLE GOLD INNOPAPER', 'INSUMO', 'm');
INSERT INTO producto (sku, nombre, tipo, unidad) VALUES ('VINILO_TEXTIL_FOIL_RAINBOW_RIPPLE_INNOPAPER', 'VINILO TEXTIL FOIL RAINBOW RIPPLE INNOPAPER', 'INSUMO', 'm');
INSERT INTO producto (sku, nombre, tipo, unidad) VALUES ('VINILO_TEXTIL_FOIL_HOLORAIN_GOLD_INNOPAPER', 'VINILO TEXTIL FOIL HOLORAIN GOLD INNOPAPER', 'INSUMO', 'm');
INSERT INTO producto (sku, nombre, tipo, unidad) VALUES ('VINILO_TEXTIL_FOIL_RAINBOW_INNOPAPER', 'VINILO TEXTIL FOIL RAINBOW INNOPAPER', 'INSUMO', 'm');
INSERT INTO producto (sku, nombre, tipo, unidad) VALUES ('VINILO_TEXTIL_FOIL_SPECTRUM_GOLD_INNOPAPER', 'VINILO TEXTIL FOIL SPECTRUM GOLD INNOPAPER', 'INSUMO', 'm');
INSERT INTO producto (sku, nombre, tipo, unidad) VALUES ('VINILO_TEXTIL_FOIL_SPECTRUM_SILVER_INNOPAPER', 'VINILO TEXTIL FOIL SPECTRUM SILVER INNOPAPER', 'INSUMO', 'm');
INSERT INTO producto (sku, nombre, tipo, unidad) VALUES ('VINILO_TEXTIL_FOIL_WHITE_INNOPAPER', 'VINILO TEXTIL FOIL WHITE INNOPAPER', 'INSUMO', 'm');
INSERT INTO producto (sku, nombre, tipo, unidad) VALUES ('VINILO_TEXTIL_FOIL_HOLORAIN_BLACK_INNOPAPER', 'VINILO TEXTIL FOIL HOLORAIN BLACK INNOPAPER', 'INSUMO', 'm');
INSERT INTO producto (sku, nombre, tipo, unidad) VALUES ('VINILO_TEXTIL_FOIL_BLACK_INNOPAPER', 'VINILO TEXTIL FOIL BLACK INNOPAPER', 'INSUMO', 'm');
INSERT INTO producto (sku, nombre, tipo, unidad) VALUES ('VINILO_TEXTIL_FOIL_LEOPARD_SILVER_INNOPAPER', 'VINILO TEXTIL FOIL LEOPARD SILVER INNOPAPER', 'INSUMO', 'm');
INSERT INTO producto (sku, nombre, tipo, unidad) VALUES ('VINILO_TEXTIL_FOIL_SPECKLE_GOLD_INNOPAPER', 'VINILO TEXTIL FOIL SPECKLE GOLD INNOPAPER', 'INSUMO', 'm');
INSERT INTO producto (sku, nombre, tipo, unidad) VALUES ('VINILO_TEXTIL_FOIL_MILITARY_INNOPAPER', 'VINILO TEXTIL FOIL MILITARY INNOPAPER', 'INSUMO', 'm');
INSERT INTO producto (sku, nombre, tipo, unidad) VALUES ('VINILO_TEXTIL_FOIL_HOLO_RAIN_SILVER_INNOPAPER', 'VINILO TEXTIL FOIL HOLO RAIN SILVER INNOPAPER', 'INSUMO', 'm');
INSERT INTO producto (sku, nombre, tipo, unidad) VALUES ('VINILO_TEXTIL_FOIL_GOLD_INNOPAPER', 'VINILO TEXTIL FOIL GOLD INNOPAPER', 'INSUMO', 'm');
INSERT INTO producto (sku, nombre, tipo, unidad) VALUES ('VINILO_TEXTIL_FOIL_BUBBLE_SILVER_INNOPAPER', 'VINILO TEXTIL FOIL BUBBLE SILVER INNOPAPER', 'INSUMO', 'm');
INSERT INTO producto (sku, nombre, tipo, unidad) VALUES ('VINILO_TEXTIL_FOIL_SPECTRUM_INNOPAPER', 'VINILO TEXTIL FOIL SPECTRUM INNOPAPER', 'INSUMO', 'm');
INSERT INTO producto (sku, nombre, tipo, unidad) VALUES ('VINILO_TEXTIL_FOIL_SILVER_INNOPAPER', 'VINILO TEXTIL FOIL SILVER INNOPAPER', 'INSUMO', 'm');
INSERT INTO producto (sku, nombre, tipo, unidad) VALUES ('VINILO_TEXTIL_FOIL_RED_INNOPAPER', 'VINILO TEXTIL FOIL RED INNOPAPER', 'INSUMO', 'm');
INSERT INTO producto (sku, nombre, tipo, unidad) VALUES ('VINILO_TEXTIL_FOIL_CHERRY_INNOPAPER', 'VINILO TEXTIL FOIL CHERRY INNOPAPER', 'INSUMO', 'm');
INSERT INTO producto (sku, nombre, tipo, unidad) VALUES ('VINILO_TEXTIL_FOIL_BUFFOLD_PLAID_RED_INNOPAPER', 'VINILO TEXTIL FOIL BUFFOLD PLAID RED INNOPAPER', 'INSUMO', 'm');
INSERT INTO producto (sku, nombre, tipo, unidad) VALUES ('VINILO_TEXTIL_FOIL_ROYAL_BLUE_INNOPAPER', 'VINILO TEXTIL FOIL ROYAL BLUE INNOPAPER', 'INSUMO', 'm');
INSERT INTO producto (sku, nombre, tipo, unidad) VALUES ('VINILO_TEXTIL_FOIL_PINK_INNOPAPER', 'VINILO TEXTIL FOIL PINK INNOPAPER', 'INSUMO', 'm');
INSERT INTO producto (sku, nombre, tipo, unidad) VALUES ('VINILO_TEXTIL_FOIL_CHROME_INNOPAPER', 'VINILO TEXTIL FOIL CHROME INNOPAPER', 'INSUMO', 'm');
INSERT INTO producto (sku, nombre, tipo, unidad) VALUES ('VINILO_TEXTIL_FOIL_COPPER_INNOPAPER', 'VINILO TEXTIL FOIL COPPER INNOPAPER', 'INSUMO', 'm');
INSERT INTO producto (sku, nombre, tipo, unidad) VALUES ('VINILO_TEXTIL_PVC_FUCHSIA_INNOPAPER', 'VINILO TEXTIL PVC FUCHSIA INNOPAPER', 'INSUMO', 'm');
INSERT INTO producto (sku, nombre, tipo, unidad) VALUES ('VINILO_TEXTIL_PVC_BLACK_INNOPAPER', 'VINILO TEXTIL PVC BLACK INNOPAPER', 'INSUMO', 'm');
INSERT INTO producto (sku, nombre, tipo, unidad) VALUES ('VINILO_TEXTIL_PVC_GOLD_INNOPAPER', 'VINILO TEXTIL PVC GOLD INNOPAPER', 'INSUMO', 'm');
INSERT INTO producto (sku, nombre, tipo, unidad) VALUES ('VINILO_TEXTIL_PVC_WHITE_INNOPAPER', 'VINILO TEXTIL PVC WHITE INNOPAPER', 'INSUMO', 'm');
INSERT INTO producto (sku, nombre, tipo, unidad) VALUES ('VINILO_TEXTIL_PVC_CLUB_AQUA_INNOPAPER', 'VINILO TEXTIL PVC CLUB AQUA INNOPAPER', 'INSUMO', 'm');
INSERT INTO producto (sku, nombre, tipo, unidad) VALUES ('VINILO_TEXTIL_PVC_ROSE_GOLD_INNOPAPER', 'VINILO TEXTIL PVC ROSE GOLD INNOPAPER', 'INSUMO', 'm');
INSERT INTO producto (sku, nombre, tipo, unidad) VALUES ('VINILO_TEXTIL_PVC_YELLOW_INNOPAPER', 'VINILO TEXTIL PVC YELLOW INNOPAPER', 'INSUMO', 'm');
INSERT INTO producto (sku, nombre, tipo, unidad) VALUES ('VINILO_TEXTIL_PVC_ROYAL_BLUE_INNOPAPER', 'VINILO TEXTIL PVC ROYAL BLUE INNOPAPER', 'INSUMO', 'm');
INSERT INTO producto (sku, nombre, tipo, unidad) VALUES ('VINILO_TEXTIL_PVC_AQUA_PASTEL_INNOPAPER', 'VINILO TEXTIL PVC AQUA PASTEL INNOPAPER', 'INSUMO', 'm');
INSERT INTO producto (sku, nombre, tipo, unidad) VALUES ('VINILO_TEXTIL_PVC_SKY_BLUE_INNOPAPER', 'VINILO TEXTIL PVC SKY BLUE INNOPAPER', 'INSUMO', 'm');
INSERT INTO producto (sku, nombre, tipo, unidad) VALUES ('VINILO_TEXTIL_PVC_DARK_BLUE_INNOPAPER', 'VINILO TEXTIL PVC DARK BLUE INNOPAPER', 'INSUMO', 'm');
INSERT INTO producto (sku, nombre, tipo, unidad) VALUES ('VINILO_TEXTIL_PVC_DARK_GREEN_INNOPAPER', 'VINILO TEXTIL PVC DARK GREEN INNOPAPER', 'INSUMO', 'm');
INSERT INTO producto (sku, nombre, tipo, unidad) VALUES ('VINILO_TEXTIL_PVC_PURPLE_INNOPAPER', 'VINILO TEXTIL PVC PURPLE INNOPAPER', 'INSUMO', 'm');
INSERT INTO producto (sku, nombre, tipo, unidad) VALUES ('VINILO_TEXTIL_PVC_SALMON_PASTEL_INNOPAPER', 'VINILO TEXTIL PVC SALMON PASTEL INNOPAPER', 'INSUMO', 'm');
INSERT INTO producto (sku, nombre, tipo, unidad) VALUES ('VINILO_TEXTIL_PVC_BROWN_INNOPAPER', 'VINILO TEXTIL PVC BROWN INNOPAPER', 'INSUMO', 'm');
INSERT INTO producto (sku, nombre, tipo, unidad) VALUES ('VINILO_TEXTIL_PVC_LIGHT_RED_INNOPAPER', 'VINILO TEXTIL PVC LIGHT RED INNOPAPER', 'INSUMO', 'm');
INSERT INTO producto (sku, nombre, tipo, unidad) VALUES ('VINILO_TEXTIL_PVC_LIME_INNOPAPER', 'VINILO TEXTIL PVC LIME INNOPAPER', 'INSUMO', 'm');
INSERT INTO producto (sku, nombre, tipo, unidad) VALUES ('VINILO_TEXTIL_PVC_MAGENTA_INNOPAPER', 'VINILO TEXTIL PVC MAGENTA INNOPAPER', 'INSUMO', 'm');
INSERT INTO producto (sku, nombre, tipo, unidad) VALUES ('VINILO_TEXTIL_PVC_BLUE_PASTEL_INNOPAPER', 'VINILO TEXTIL PVC BLUE PASTEL INNOPAPER', 'INSUMO', 'm');
INSERT INTO producto (sku, nombre, tipo, unidad) VALUES ('VINILO_TEXTIL_PVC_GRAY_INNOPAPER', 'VINILO TEXTIL PVC GRAY INNOPAPER', 'INSUMO', 'm');
INSERT INTO producto (sku, nombre, tipo, unidad) VALUES ('VINILO_TEXTIL_PVC_PURPLE_PASTEL_INNOPAPER', 'VINILO TEXTIL PVC PURPLE PASTEL INNOPAPER', 'INSUMO', 'm');
INSERT INTO producto (sku, nombre, tipo, unidad) VALUES ('VINILO_TEXTIL_PVC_BEIGE_INNOPAPER', 'VINILO TEXTIL PVC BEIGE INNOPAPER', 'INSUMO', 'm');
INSERT INTO producto (sku, nombre, tipo, unidad) VALUES ('VINILO_TEXTIL_PVC_SILVER_INNOPAPER', 'VINILO TEXTIL PVC SILVER INNOPAPER', 'INSUMO', 'm');
INSERT INTO producto (sku, nombre, tipo, unidad) VALUES ('VINILO_TEXTIL_PVC_NAVY_BLUE_INNOPAPER', 'VINILO TEXTIL PVC NAVY BLUE INNOPAPER', 'INSUMO', 'm');
INSERT INTO producto (sku, nombre, tipo, unidad) VALUES ('VINILO_TEXTIL_PVC_NEON_FUCHSIA_INNOPAPER', 'VINILO TEXTIL PVC NEON FUCHSIA INNOPAPER', 'INSUMO', 'm');
INSERT INTO producto (sku, nombre, tipo, unidad) VALUES ('VINILO_TEXTIL_PVC_LIGHT_BEIGE_INNOPAPER', 'VINILO TEXTIL PVC LIGHT BEIGE INNOPAPER', 'INSUMO', 'm');
INSERT INTO producto (sku, nombre, tipo, unidad) VALUES ('VINILO_TEXTIL_PVC_TURQUOISE_INNOPAPER', 'VINILO TEXTIL PVC TURQUOISE INNOPAPER', 'INSUMO', 'm');
INSERT INTO producto (sku, nombre, tipo, unidad) VALUES ('VINILO_TEXTIL_PVC_PINK_INNOPAPER', 'VINILO TEXTIL PVC PINK INNOPAPER', 'INSUMO', 'm');
INSERT INTO producto (sku, nombre, tipo, unidad) VALUES ('VINILO_TEXTIL_PVC_LEMON_YELLOW_INNOPAPER', 'VINILO TEXTIL PVC LEMON YELLOW INNOPAPER', 'INSUMO', 'm');
INSERT INTO producto (sku, nombre, tipo, unidad) VALUES ('VINILO_TEXTIL_PVC_NEON_PINK_INNOPAPER', 'VINILO TEXTIL PVC NEON PINK INNOPAPER', 'INSUMO', 'm');
INSERT INTO producto (sku, nombre, tipo, unidad) VALUES ('VINILO_TEXTIL_PVC_MINT_PASTEL_INNOPAPER', 'VINILO TEXTIL PVC MINT PASTEL INNOPAPER', 'INSUMO', 'm');
INSERT INTO producto (sku, nombre, tipo, unidad) VALUES ('VINILO_TEXTIL_PVC_NAVY_INNOPAPER', 'VINILO TEXTIL PVC NAVY INNOPAPER', 'INSUMO', 'm');
INSERT INTO producto (sku, nombre, tipo, unidad) VALUES ('VINILO_TEXTIL_PVC_GOLDEN_YELLOW_INNOPAPER', 'VINILO TEXTIL PVC GOLDEN YELLOW INNOPAPER', 'INSUMO', 'm');
INSERT INTO producto (sku, nombre, tipo, unidad) VALUES ('VINILO_TEXTIL_PVC_CAMEL_INNOPAPER', 'VINILO TEXTIL PVC CAMEL INNOPAPER', 'INSUMO', 'm');
INSERT INTO producto (sku, nombre, tipo, unidad) VALUES ('VINILO_TEXTIL_PVC_LIGHT_PINK_INNOPAPER', 'VINILO TEXTIL PVC LIGHT PINK INNOPAPER', 'INSUMO', 'm');
INSERT INTO producto (sku, nombre, tipo, unidad) VALUES ('VINILO_TEXTIL_PVC_ORANGE_INNOPAPER', 'VINILO TEXTIL PVC ORANGE INNOPAPER', 'INSUMO', 'm');
INSERT INTO producto (sku, nombre, tipo, unidad) VALUES ('VINILO_TEXTIL_PVC_NEON_ORANGE_INNOPAPER', 'VINILO TEXTIL PVC NEON ORANGE INNOPAPER', 'INSUMO', 'm');
INSERT INTO producto (sku, nombre, tipo, unidad) VALUES ('VINILO_TEXTIL_PVC_AQUA_INNOPAPER', 'VINILO TEXTIL PVC AQUA INNOPAPER', 'INSUMO', 'm');
INSERT INTO producto (sku, nombre, tipo, unidad) VALUES ('DTF_TEXTIL_NONE_NONE_NONE', 'DTF TEXTIL NONE NONE NONE', 'INSUMO', 'm');
INSERT INTO producto (sku, nombre, tipo, unidad) VALUES ('DTF_UV_NONE_NONE_NONE', 'DTF UV NONE NONE NONE', 'INSUMO', 'm');
INSERT INTO producto (sku, nombre, tipo, unidad) VALUES ('STICKERADHESIVO_NONE_NONE_NONE', 'STICKER/ADHESIVO NONE NONE NONE', 'INSUMO', 'm');
INSERT INTO producto (sku, nombre, tipo, unidad) VALUES ('TELA_PVC_NONE_NONE_NONE', 'TELA PVC NONE NONE NONE', 'INSUMO', 'm');